version: '3.8'

services:
  # Stock Analysis Agent Application
  stock-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-agent
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  default:
    driver: bridge 